### ISSUE TITLE
Yaml statt eigener Syntax

### ISSUE THREAD

**Issue by gharlan** [FriendsOfREDAXO/properties#3]
Ich würde eher Yaml nutzen statt einer eigenen Syntax (auch wenn die in den Sprachdateien aus historischen Gründen auch verwendet wird).

Mit Yaml könnte man auch echte Array-"Properties" (beliebig tief verschachtelt) schreiben:

```yaml
news:
    limit: 10
    detailArticle: 123
```
